{% set name = "rocm-comgr" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCm-CompilerSupport/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 737b110d9402509db200ee413fb139a78369cf517453395b96bda52d0aa362b9
  patches:
    - patches/5f10322be56320b185cda2ef1765e051b3c9c370.patch
    - patches/b4a5e883c7f1045c0a8257934f98915b48dea545.patch
    - patches/6e2b1bd74dc7aa8e08add392f69d37ba3071576e.patch
    - patches/f6b2c101730025e48b1734678316ef1c42aefcb4.patch
    - patches/8276083301409001ec7643e68f5ad58b057c21fd.patch
    - patches/missing_include.diff

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 17.*
    - llvmdev 17.*
    - llvm
    - lld
    - zlib
    - rocm-device-libs
    - rocm-cmake  {{ version }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/ROCm/ROCm-CompilerSupport
  license: NCSA
  license_file: LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - isuruf
