{% set name = "rocm-comgr" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 6bd9912441de6caf6b26d1323e1c899ecd14ff2431874a2f5883d3bc5212db34
  patches:
    - patches/deactivate-flaky-tests.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - clangdev 17.*
    - llvmdev 17.*
    - llvm
    - lld
    - zlib
    - zstd
    - rocm-device-libs
    - rocm-cmake  {{ version }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/ROCm/ROCm-CompilerSupport
  license: NCSA
  license_file: amd/comgr/LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
