{% set name = "rocm-comgr" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/roc-{{ version }}.tar.gz
  sha256: 7ec40ca2b55354113f2ab5dde1d98b241795b63776f1715851cac969c3d4e2ad
  patches:
    - rocm-comgr-2.6.0-unbundle-yaml-cpp.patch
    - link_to_llvm_dynamic.diff

build:
  number: 0
  skip: True  # [not linux]
  #merge_build_host: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 9.*
    - llvmdev 9.*
    - llvm
    - lld
    - yaml-cpp
    - rocm-device-libs
  run:
    - {{ pin_compatible("yaml-cpp", max_pin="x.x") }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport
  license: BSD-3-Clause
  license_family: BSD
  license_file: lib/comgr/LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - isuruf
