{% set name = "rocm-comgr" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 6bd9912441de6caf6b26d1323e1c899ecd14ff2431874a2f5883d3bc5212db34
  # patches:
  #   - patches/8276083301409001ec7643e68f5ad58b057c21fd.patch
  #   - patches/missing_include.diff

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - make
  host:
    - clangdev 17.*
    - llvmdev 17.*
    - llvm
    - lld
    - zlib
    - rocm-device-libs
    - rocm-cmake  {{ version }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/ROCm/ROCm-CompilerSupport
  license: NCSA
  license_file: LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
