{% set name = "rocm-comgr" %}
{% set version = "6.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 4df9aba24e574edf23844c0d2d9dda112811db5c2b08c9428604a21b819eb23d
  patches:
    - patches/llvm-19-compatibility.patch
    - patches/deactivate-flaky-tests.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - clangdev 19.*
    - llvmdev 19.*
    - llvm
    - lld
    - zlib
    - zstd
    - rocm-device-libs
    - rocm-cmake  {{ version }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/ROCm/llvm-project/tree/amd-staging/amd/comgr
  license: NCSA
  license_file: amd/comgr/LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
